# Generated by Django 3.2.8 on 2022-01-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(verbose_name='max_length=400')),
                ('email', models.EmailField(max_length=254, verbose_name='max_length=254')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
